### PR TITLE
Change rails version to "< 5.2" in dependencies

### PR DESCRIPTION
**Pull request by gambala**
For proper Rails 5.1 support

### CODE REVIEW

**Comment by laserlemon** [comment]
Thank you! Could you please also add a Rails 5.2 gemfile and update `travis.yml` accordingly?

**Comment by gambala** [comment]
Should I add gemfile into gemfiles array or into matrix hash for both (or not) ruby versions?

image

**Comment by laserlemon** [comment]
The new gem file should be added to the matrix > include array because Rails >= 5 dropped support for Rubies < 2.2.

**Comment by VGleb** [comment]
+

**Comment by laserlemon** [comment]
New version released: v2.1.1! Thank you! :clap:

**Pull request merged**
