### PR TITLE
Include Rails 5.2 support

### PR DESCRIPTION
**Pull request by GeorgeKaraszi**
Fixes https://github.com/collectiveidea/interactor-rails/issues/18

And included the latest Ruby 2.5.1 test for travis.

### CODE REVIEW

**Comment by n-n1ks** [comment]
Great job!
Merge it please! :-)

**Comment by laserlemon** [comment]
@GeorgeKaraszi Thank you for your first contribution! :tada: If I may, can I ask you to make a few changes?

1. Please amend your commit to remove the gemspec version bump. That's best left to the maintainer after your changes are merged. There are a couple reasons for this:
    - There's no guarantee in which order pull requests will be accepted and merged, so this version number might quickly become incorrect.
    - The maintainers know best _how_ to bump the version, whether it should be major, minor, or patch. In this particular case, I'd probably only bump the patch version. There are interesting [discussions on this topic](https://github.com/semver/semver/issues/148).
2. Can you convert `gemfiles/rails51+.gemfile` to `gemfiles/rails52.gemfile` using `gemfiles/rails51.gemfile` as a template? That way, we're sure that Rails 5.2 is covered going forward.
3. Changing the `interactor-rails` dependency on `rails` to `< 6.0` is premature. We have no idea whether it will work with Rails 5.3. Although this periodic version bumping process is a little painful, it's also important. Please change the requirement to `< 5.3`.
4. For future contributions, I'd keep your PR as focused as possible. Adding support for the newest Ruby version is great and a welcomed change but it also has the potential to hold up Rails support if the maintainers had some concerns around it. In this case, no big deal (if it passes)!

Again, thank you for your great and speedy contribution!

@n-n1ks You forgot [step #5](https://github.com/collectiveidea/interactor-rails/blob/master/CONTRIBUTING.md#how-do-i-contributehttps://github.com/collectiveidea/interactor-rails/blob/master/CONTRIBUTING.md#how-do-i-contribute).

**Comment by GeorgeKaraszi** [comment]
@laserlemon Yea sorry about the version bump (force of habit >_>). I amended and squashed the changes.

**Comment by drn** [comment]
@laserlemon - Anything else blocking this from being merged in + a gem version released? Happy to help out here if anything is needed. Unfortunately, this is currently preventing us from upgrading to Rails 5.2 (which fixes a race condition I've looking forward to getting squashed :)). Thanks!!

**Comment by GeorgeKaraszi** [comment]
@laserlemon Don't mean to be nag, but we are going on week 2 with no official word on what's going on.. Is there anything I or anyone else can do to get this moving?

**Comment by laserlemon** [comment]
Sorry, no nothing further than needs to be done. I'll cut a new version this morning! Thank you all for your work to get this out the door and sorry for the delay!! 👏🎊👏

**Comment by laserlemon** [comment]
Version 2.2.0 :ship:d! Thank you, @GeorgeKaraszi! I did end up bumping the minor version because I dropped Ruby 2.2 (now EOL) from official support (although there should be nothing breaking as of today).

**Pull request merged**
