### PR TITLE
Use rails_helper instead of spec_helper

### PR DESCRIPTION
**Pull request by fzf**

### CODE REVIEW

**Comment by fzf** [comment]
failures seem to be due to `Bundler could not find compatible versions for gem "bundler":` which is outside my control

**Comment by fzf** [comment]
@laserlemon is there anything else this needs to be merged in? This should fix https://github.com/collectiveidea/interactor-rails/issues/21

**Comment by fzf** [comment]
@gaffneyc seems like you are the maintainer at this point, is there any reason not to switch to `rails_helper`?

**Comment by wmulligan87** [comment]
bumping this, wasted some time figuring out why my generated interactor specs weren't working...

**Pull request closed without merging**
